version: "3.3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./pk.pk:/pk.pk
      - ./cert.cert:/cert.cert
      - ../nodejs-example/public:/app/public
    ports:
      - "8880:80"
      - "8443:443"
    deploy:
      resources:
        limits:
          cpus: '4'

    command: "nginx -g 'daemon off;'"
  nodejs: 
    restart: always
    build:
      context: ../nodejs-example
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '4'  
  db:
    restart: always
    image: sameersbn/postgresql:10
    ports:
      - "5000:5432"
    environment:
      - DB_USER=example
      - DB_PASS=example
      - DB_NAME=people
